version: 2
jobs:
  deploy-staging:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: NODE_ENV=production CI="" yarn build
      - run: sudo apt-get install python-dev python-pip
      - run: sudo pip install awscli
      - run: aws configure set preview.cloudfront true
      - run: aws s3 sync build s3://com-amplehills-staging/ --delete
      - run: aws cloudfront create-invalidation --distribution-id E3U7R1C3HO37LU --paths '/*'

  deploy-production:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: NODE_ENV=production CI="" yarn build
      - run: sudo apt-get install python-dev python-pip
      - run: sudo pip install awscli
      - run: aws configure set preview.cloudfront true
      - run: aws s3 sync build s3://com-amplehills-production/ --delete
      - run: aws cloudfront create-invalidation --distribution-id E1KZEDDGQAGLOF --paths '/*'

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - deploy-staging:
          filters:
            branches:
              only: staging
      - deploy-production:
          filters:
            branches:
              only: production
